// src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const router = useRouter()
const userStore = useUserStore()

const phone = ref('')
const password = ref('')
const loading = ref(false)
const error = ref('')

const handleLogin = async () => {
  error.value = ''

  if (!phone.value || !password.value) {
    error.value = '请输入手机号和密码'
    return
  }

  loading.value = true

  try {
    await userStore.doLogin(phone.value, password.value)
    const role = userStore.primaryRole || 'student'
    const redirectMap: Record<string, string> = {
      admin: '/admin/dashboard',
      interviewer: '/interviewer/tasks',
      student: '/student/apply'
    }
    router.push(redirectMap[role] || '/')
  } catch (err: any) {
    console.error('登录错误:', err)
    // 提示更友好的错误信息
    error.value = '手机号或密码错误'
  } finally {
    loading.value = false
  }
}

const goToRegister = () => {
  router.push('/register')
}

const goToForgetPassword = () => {
  router.push('/forget-password')
}
</script>

<template>
  <div class="min-h-screen w-full bg-white flex items-center justify-center p-6">
    <div class="w-full max-w-sm flex flex-col gap-6">
      <!-- 标题 -->
      <div class="flex flex-col items-center gap-2 text-center">
        <h1 class="text-2xl font-bold">社团面试系统</h1>
        <p class="text-muted-foreground text-sm">请登录您的账号</p>
      </div>

      <!-- 表单 -->
      <form @submit.prevent="handleLogin" class="flex flex-col gap-4">
        <!-- 错误提示 -->
        <div v-if="error" class="p-3 text-sm text-red-600 bg-red-50 rounded-md">
          {{ error }}
        </div>

        <div class="grid gap-2">
          <Label for="phone">手机号</Label>
          <Input
            id="phone"
            v-model="phone"
            type="tel"
            placeholder="请输入手机号"
            required
          />
        </div>

        <div class="grid gap-2">
          <Label for="password">密码</Label>
          <Input
            id="password"
            v-model="password"
            type="password"
            placeholder="请输入密码"
            required
          />
        </div>

        <!-- 忘记密码 -->
        <div class="flex justify-end">
          <button
            type="button"
            class="text-sm text-primary hover:underline"
            @click="goToForgetPassword"
          >
            忘记密码？
          </button>
        </div>

        <Button type="submit" class="w-full" :disabled="loading">
          <span v-if="loading">登录中...</span>
          <span v-else>登录</span>
        </Button>
      </form>

      <!-- 注册入口 -->
      <p class="text-center text-sm text-muted-foreground">
        还没有账号？
        <button
          type="button"
          class="text-primary hover:underline font-medium"
          @click="goToRegister"
        >
          立即注册
        </button>
      </p>

      <!-- 底部条款 -->
      <p class="text-center text-xs text-muted-foreground">
        登录即表示同意
        <a href="#" class="underline underline-offset-4 hover:text-primary">服务条款</a>
        和
        <a href="#" class="underline underline-offset-4 hover:text-primary">隐私政策</a>
      </p>
    </div>
  </div>
</template>

// frontend/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { login } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { extractErrorMessage } from "@/lib/utils";

export default function LoginPage() {
  const router = useRouter();
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      await login(phone, password);
      router.push("/dashboard");
    } catch (err: any) {
      setError(extractErrorMessage(err));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full space-y-8 p-8 bg-white rounded-lg shadow-md">
        <div>
          <h2 className="text-center text-3xl font-bold text-gray-900">
            登录
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            校园社团招新与面试管理系统
          </p>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}
          <div className="space-y-4">
            <div>
              <label htmlFor="phone" className="block text-sm font-medium text-gray-700">
                手机号
              </label>
              <input
                id="phone"
                type="tel"
                required
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                placeholder="请输入手机号"
              />
            </div>
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                密码
              </label>
              <input
                id="password"
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                placeholder="请输入密码"
              />
            </div>
          </div>
          <div>
            <Button
              type="submit"
              className="w-full"
              disabled={loading}
            >
              {loading ? "登录中..." : "登录"}
            </Button>
          </div>
          <div className="text-center">
            <a href="/register" className="text-sm text-primary hover:underline">
              还没有账号？立即注册
            </a>
          </div>
        </form>
      </div>
    </div>
  );
}
